# Generated by Django 4.1 on 2022-09-02 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("company", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Kullanıcı ID",
                    ),
                ),
                ("isim", models.CharField(max_length=128, verbose_name="İsim")),
                ("soyisim", models.CharField(max_length=128, verbose_name="Soyisim")),
                (
                    "email",
                    models.EmailField(
                        max_length=128, unique=True, verbose_name="Email"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Şifre")),
                (
                    "uyelik_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Üyelik Tarihi"
                    ),
                ),
                (
                    "son_giris",
                    models.DateTimeField(auto_now=True, verbose_name="Son Oturum"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Yönetici"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif Hesap"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Personel"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="Genel Yönetici"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "takip",
                    models.ManyToManyField(
                        to="company.company", verbose_name="Takip Edilen Şirketler"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
            },
        ),
    ]
