# Generated by Django 4.1 on 2022-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_ulke"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="isim",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="İsim"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="soyisim",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Soyisim"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="takip",
            field=models.ManyToManyField(
                blank=True, to="company.company", verbose_name="Takip Edilen Şirketler"
            ),
        ),
    ]
