# Generated by Django 4.1 on 2022-09-02 20:49

import company.models
from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "kurulus_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Kuruluş ID",
                    ),
                ),
                (
                    "kurulus_adi",
                    models.CharField(max_length=256, verbose_name="Kuruluş Adı"),
                ),
                (
                    "kurulus_logo",
                    models.ImageField(
                        upload_to=company.models.upload_logo,
                        verbose_name="Kuruluş Logo",
                    ),
                ),
                (
                    "kurulus_turu",
                    models.CharField(
                        choices=[
                            ("Şahıs", "Şahıs"),
                            ("Büyük İşletme", "Büyük İşletme"),
                            ("KOBİ", "KOBİ"),
                            ("STK", "STK"),
                        ],
                        max_length=256,
                        verbose_name="Kuruluş Türü",
                    ),
                ),
                ("ulke", django_countries.fields.CountryField(max_length=2)),
                (
                    "website",
                    models.URLField(max_length=128, verbose_name="Kuruluş Websitesi"),
                ),
                (
                    "calisan_sayisi",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=6,
                        verbose_name="Kuruluş Çalışan Sayısı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şirket",
                "verbose_name_plural": "Şirketler",
            },
        ),
    ]
