# Generated by Django 4.1 on 2022-09-03 12:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="ulke",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="Ülke"
            ),
        ),
    ]
